version: '3.9'

services:
  db:
    image: postgres:alpine
    container_name: postgres-pix-keymanager-grpc
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pix-keymanager-grpc
    ports:
      - "5432:5432"

  bcb:
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix"
    ports:
      - "8082:8082"

  erp-itau:
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp"
    ports:
      - "9091:9091"