micronaut:
  application:
    name: pixKeymanagerGrpc

datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/pix-keymanager-grpc`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

clients:
  itau: http://localhost:9091/api/v1
  bcb: http://localhost:8082/api/v1/pix/keys